import type { Metadata } from "next";
import React from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "./component/header";
import { LocationProvider } from "@/contex/locationContex";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <LocationProvider>
            <header className="flex items-center p-4 bg-gray-100">
              <Header />
            </header>
            <main className="container mx-auto p-4">{children}</main>
            <footer className="flex items-center justify-center p-4 bg-gray-100">
              <p className="text-sm text-gray-600">
                © {new Date().getFullYear()} Google Map Location. All rights
                reserved.
              </p>
            </footer>
          </LocationProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
