import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import Header from "./component/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="flex items-center  p-4 bg-gray-100">
            <Header />
          </header>
          <main className="container mx-auto p-4">
            <h2 className="text-2xl font-semibold mb-4">Welcome to the App</h2>
            {children}
          </main>
          <footer className="flex items-center justify-center p-4 bg-gray-100">
            <p className="text-sm text-gray-600">
              © {new Date().getFullYear()} Google Map Location. All rights
              reserved.
            </p>
          </footer>
          {/* Render the children components */}
        </body>
      </html>
    </ClerkProvider>
  );
}
